spring:
  application:
    name: m2i2
  datasource:
    url: jdbc:mysql://localhost:3307/spring_td?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      platform: test
      mode: always